DROP DATABASE Lumina_Games;
CREATE DATABASE IF NOT EXISTS Lumina_Games;

USE Lumina_Games;

CREATE TABLE IF NOT EXISTS users(
id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(120) NOT NULL,
email VARCHAR(160) NOT NULL UNIQUE,
password VARCHAR(255) NOT NULL,
create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS categories(
id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(120) NOT NULL,
description VARCHAR(255),
create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS 	games(
id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
title VARCHAR(150) NOT NULL,
description TEXT,
release_date DATE,
age_rating VARCHAR(10),
price DECIMAL(10,2),
stock INT DEFAULT 0,
cover_url VARCHAR(300),
create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
FULLTEXT KEY ft_games_title_desc (title, description)
);

CREATE TABLE IF NOT EXISTS game_categories(
game_id INT UNSIGNED NOT NULL,
category_id INT UNSIGNED NOT NULL,
PRIMARY KEY (game_id, category_id),
CONSTRAINT fk_gc_game FOREIGN KEY(game_id) REFERENCES games(id) ON DELETE CASCADE,
CONSTRAINT fk_gc_cat  FOREIGN KEY(category_id) REFERENCES categories(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS platforms(
id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(60) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS game_platforms(
game_id INT UNSIGNED NOT NULL,
platform_id INT UNSIGNED NOT NULL,
PRIMARY KEY (game_id, platform_id),
CONSTRAINT fk_gp_game FOREIGN KEY(game_id) REFERENCES games(id) ON DELETE CASCADE,
CONSTRAINT fk_gp_platform FOREIGN KEY(platform_id) REFERENCES platforms(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ratings(
id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
user_id INT UNSIGNED NOT NULL,
game_id INT UNSIGNED NOT NULL,
score TINYINT UNSIGNED NOT NULL CHECK (score BETWEEN 1 AND 5),
comment TEXT,
create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT fk_r_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
CONSTRAINT fk_r_game FOREIGN KEY(game_id) REFERENCES games(id) ON DELETE CASCADE
);

CREATE TABLE developers(
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(120) NOT NULL
);

CREATE TABLE publishers(
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(120) NOT NULL UNIQUE
);

CREATE TABLE game_developers(
  game_id INT UNSIGNED NOT NULL,
  developer_id INT UNSIGNED NOT NULL,
  PRIMARY KEY (game_id, developer_id),
  CONSTRAINT fk_gd_game FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE,
  CONSTRAINT fk_gd_dev  FOREIGN KEY (developer_id) REFERENCES developers(id) ON DELETE CASCADE
);

CREATE TABLE game_publishers(
  game_id INT UNSIGNED NOT NULL,
  publisher_id INT UNSIGNED NOT NULL,
  PRIMARY KEY (game_id, publisher_id),
  CONSTRAINT fk_gpbl_game FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE,
  CONSTRAINT fk_gpbl_pub  FOREIGN KEY (publisher_id) REFERENCES publishers(id) ON DELETE CASCADE
);